-- CREARE TABELE
CREATE TABLE categorii_produse (
    id INTEGER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    nume VARCHAR2(50),
    descriere VARCHAR2(255),
    PRIMARY KEY (id)
);
COMMIT;

CREATE TABLE stoc_produse (
    id INTEGER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    id_categorie INTEGER,
    putere_termica_kWh NUMBER,
    randament_energetic NUMBER,
    cantitate NUMBER,
    pret NUMBER,
    PRIMARY KEY (id),
    FOREIGN KEY (id_categorie) REFERENCES categorii_produse(id)
);
COMMIT;

CREATE TABLE discount_si_comision_categorie (
    id INTEGER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    id_categorie INTEGER,
    valoare_discount NUMBER,
    valoare_comision NUMBER,
    PRIMARY KEY (id),
    FOREIGN KEY (id_categorie) REFERENCES categorii_produse(id)
);
COMMIT;

CREATE TABLE angajati (
    id INTEGER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    nume VARCHAR2(50),
    prenume VARCHAR2(50),
    functie VARCHAR2(50),
    data_angajare DATE,
    salariu NUMBER,
    comision NUMBER,
    PRIMARY KEY (id)
);
COMMIT;

CREATE TABLE vanzari_produse (
    id INTEGER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    id_produs INTEGER,
    cantitate NUMBER,
    data_vanzare DATE,
    id_angajat INTEGER,
    PRIMARY KEY (id),
    FOREIGN KEY (id_produs) REFERENCES stoc_produse(id),
    FOREIGN KEY (id_angajat) REFERENCES angajati(id)
);
COMMIT;